// =============================================================================
// TAX CATEGORIES - Single Source of Truth
// =============================================================================
// Each category maps to:
//   - An IRS form and specific line number
//   - A TurboTax TXF code (for .txf export)
//   - A "type" (income, deduction, credit, info-only)
//   - A "schedule" grouping for organization
// =============================================================================

export const TAX_YEAR_CURRENT = new Date().getFullYear();

// -----------------------------------------------------------------------------
// TYPE ENUMS
// -----------------------------------------------------------------------------
export const TAX_TYPES = {
  INCOME: 'income',
  DEDUCTION: 'deduction',
  CREDIT: 'credit',
  ADJUSTMENT: 'adjustment', // Above-the-line (Schedule 1)
  PAYMENT: 'payment',        // Estimated tax payments, etc.
  PERSONAL: 'personal',      // Non-deductible personal expense
};

export const TAX_SCHEDULES = {
  W2: 'W-2',
  FORM_1099: '1099 Forms',
  SCHEDULE_A: 'Schedule A (Itemized Deductions)',
  SCHEDULE_B: 'Schedule B (Interest & Dividends)',
  SCHEDULE_C: 'Schedule C (Self-Employment)',
  SCHEDULE_D: 'Schedule D (Capital Gains)',
  SCHEDULE_E: 'Schedule E (Rental/Royalty)',
  SCHEDULE_1: 'Schedule 1 (Additional Income/Adjustments)',
  SCHEDULE_2: 'Schedule 2 (Additional Taxes)',
  SCHEDULE_3: 'Schedule 3 (Additional Credits)',
  FORM_1040: 'Form 1040',
  PERSONAL: 'Personal (Non-Deductible)',
  OTHER: 'Other',
};

// -----------------------------------------------------------------------------
// TAX CATEGORIES
// -----------------------------------------------------------------------------
// IMPORTANT: TXF codes (txfCode) are based on the TurboTax TXF Standard.
// Values reflect commonly used codes as of the 2024 tax year. Always verify
// against current IRS form instructions before filing.
// -----------------------------------------------------------------------------
export const TAX_CATEGORIES = [
  // ===========================================================================
  // INCOME - W-2 Wages
  // ===========================================================================
  {
    id: 'w2_wages',
    label: 'W-2 Wages',
    type: TAX_TYPES.INCOME,
    schedule: TAX_SCHEDULES.W2,
    form: 'Form 1040',
    line: 'Line 1a',
    lineDescription: 'Total amount from Form(s) W-2, box 1',
    txfCode: 'N260',
    description: 'Salary and wages reported on W-2',
    requiresDoc: 'W-2 form from employer',
    notes: 'Enter gross wages from W-2 Box 1',
  },
  {
    id: 'w2_tips',
    label: 'W-2 Tips Not Reported',
    type: TAX_TYPES.INCOME,
    schedule: TAX_SCHEDULES.W2,
    form: 'Form 1040',
    line: 'Line 1c',
    lineDescription: 'Tip income not reported on line 1a',
    txfCode: 'N261',
    description: 'Tips received but not reported to employer',
    notes: 'Use Form 4137 if required',
  },

  // ===========================================================================
  // INCOME - 1099 Forms
  // ===========================================================================
  {
    id: '1099_nec',
    label: '1099-NEC Non-Employee Compensation',
    type: TAX_TYPES.INCOME,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 1',
    lineDescription: 'Gross receipts or sales',
    txfCode: 'N292',
    description: 'Self-employment income from 1099-NEC',
    requiresDoc: '1099-NEC form',
    notes: 'Report on Schedule C as business income',
  },
  {
    id: '1099_misc_other',
    label: '1099-MISC Other Income',
    type: TAX_TYPES.INCOME,
    schedule: TAX_SCHEDULES.SCHEDULE_1,
    form: 'Schedule 1',
    line: 'Line 8z',
    lineDescription: 'Other income (list type and amount)',
    txfCode: 'N677',
    description: 'Miscellaneous income from 1099-MISC',
    requiresDoc: '1099-MISC form',
  },
  {
    id: '1099_int',
    label: '1099-INT Interest Income',
    type: TAX_TYPES.INCOME,
    schedule: TAX_SCHEDULES.SCHEDULE_B,
    form: 'Schedule B',
    line: 'Part I, Line 1',
    lineDescription: 'List name of payer and amount',
    txfCode: 'N287',
    description: 'Interest income from banks/investments',
    requiresDoc: '1099-INT form',
    notes: 'Required if total interest exceeds $1,500',
  },
  {
    id: '1099_div_ordinary',
    label: '1099-DIV Ordinary Dividends',
    type: TAX_TYPES.INCOME,
    schedule: TAX_SCHEDULES.SCHEDULE_B,
    form: 'Form 1040',
    line: 'Line 3b',
    lineDescription: 'Ordinary dividends',
    txfCode: 'N286',
    description: 'Ordinary dividends (1099-DIV Box 1a)',
    requiresDoc: '1099-DIV form',
  },
  {
    id: '1099_div_qualified',
    label: '1099-DIV Qualified Dividends',
    type: TAX_TYPES.INCOME,
    schedule: TAX_SCHEDULES.FORM_1040,
    form: 'Form 1040',
    line: 'Line 3a',
    lineDescription: 'Qualified dividends',
    txfCode: 'N623',
    description: 'Qualified dividends (1099-DIV Box 1b)',
    notes: 'Subject to capital gains tax rates',
  },
  {
    id: '1099_b_short_term',
    label: '1099-B Short-Term Capital Gains/Losses',
    type: TAX_TYPES.INCOME,
    schedule: TAX_SCHEDULES.SCHEDULE_D,
    form: 'Form 8949/Schedule D',
    line: 'Part I',
    lineDescription: 'Short-term transactions (held ≤1 year)',
    txfCode: 'N321',
    description: 'Investment sales held 1 year or less',
    requiresDoc: '1099-B form and cost basis records',
  },
  {
    id: '1099_b_long_term',
    label: '1099-B Long-Term Capital Gains/Losses',
    type: TAX_TYPES.INCOME,
    schedule: TAX_SCHEDULES.SCHEDULE_D,
    form: 'Form 8949/Schedule D',
    line: 'Part II',
    lineDescription: 'Long-term transactions (held >1 year)',
    txfCode: 'N323',
    description: 'Investment sales held more than 1 year',
    requiresDoc: '1099-B form and cost basis records',
  },
  {
    id: '1099_r_distribution',
    label: '1099-R Retirement Distribution',
    type: TAX_TYPES.INCOME,
    schedule: TAX_SCHEDULES.FORM_1040,
    form: 'Form 1040',
    line: 'Line 5b',
    lineDescription: 'Pensions and annuities - taxable amount',
    txfCode: 'N623',
    description: 'Distributions from IRAs, 401(k)s, pensions',
    requiresDoc: '1099-R form',
  },
  {
    id: 'ssa_benefits',
    label: 'Social Security Benefits (SSA-1099)',
    type: TAX_TYPES.INCOME,
    schedule: TAX_SCHEDULES.FORM_1040,
    form: 'Form 1040',
    line: 'Line 6a',
    lineDescription: 'Social security benefits',
    txfCode: 'N266',
    description: 'Social Security benefits received',
    requiresDoc: 'SSA-1099 form',
  },

  // ===========================================================================
  // INCOME - Schedule E (Rental)
  // ===========================================================================
  {
    id: 'rental_income',
    label: 'Rental Income',
    type: TAX_TYPES.INCOME,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 3',
    lineDescription: 'Rents received',
    txfCode: 'N325',
    description: 'Rental property income',
    notes: 'Report per property',
  },
  {
    id: 'royalty_income',
    label: 'Royalty Income',
    type: TAX_TYPES.INCOME,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 4',
    lineDescription: 'Royalties received',
    txfCode: 'N326',
    description: 'Royalty income',
  },

  // ===========================================================================
  // INCOME - Other
  // ===========================================================================
  {
    id: 'gambling_winnings',
    label: 'Gambling Winnings',
    type: TAX_TYPES.INCOME,
    schedule: TAX_SCHEDULES.SCHEDULE_1,
    form: 'Schedule 1',
    line: 'Line 8b',
    lineDescription: 'Gambling income',
    txfCode: 'N280',
    description: 'Gambling winnings (W-2G or otherwise)',
  },
  {
    id: 'unemployment',
    label: 'Unemployment Compensation',
    type: TAX_TYPES.INCOME,
    schedule: TAX_SCHEDULES.SCHEDULE_1,
    form: 'Schedule 1',
    line: 'Line 7',
    lineDescription: 'Unemployment compensation',
    txfCode: 'N267',
    description: 'Unemployment benefits received',
    requiresDoc: '1099-G form',
  },
  {
    id: 'state_tax_refund',
    label: 'State/Local Tax Refund',
    type: TAX_TYPES.INCOME,
    schedule: TAX_SCHEDULES.SCHEDULE_1,
    form: 'Schedule 1',
    line: 'Line 1',
    lineDescription: 'Taxable refunds of state/local income taxes',
    txfCode: 'N272',
    description: 'State tax refund (may be taxable)',
    notes: 'Taxable only if you itemized last year',
  },

  // ===========================================================================
  // SCHEDULE A - ITEMIZED DEDUCTIONS
  // ===========================================================================
  {
    id: 'medical_expenses',
    label: 'Medical & Dental Expenses',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_A,
    form: 'Schedule A',
    line: 'Line 1',
    lineDescription: 'Medical and dental expenses',
    txfCode: 'N472',
    description: 'Out-of-pocket medical costs (doctor, prescriptions, etc.)',
    notes: 'Only amount exceeding 7.5% of AGI is deductible',
    requiresDoc: 'Receipts, insurance statements',
  },
  {
    id: 'medical_insurance_premiums',
    label: 'Health Insurance Premiums (after-tax)',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_A,
    form: 'Schedule A',
    line: 'Line 1',
    lineDescription: 'Medical insurance premiums',
    txfCode: 'N473',
    description: 'Premiums paid with after-tax dollars',
    notes: 'Do NOT include premiums deducted pre-tax from paycheck',
  },
  {
    id: 'state_local_income_tax',
    label: 'State & Local Income Taxes (SALT)',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_A,
    form: 'Schedule A',
    line: 'Line 5a',
    lineDescription: 'State and local income taxes or general sales taxes',
    txfCode: 'N522',
    description: 'State/local income tax paid',
    notes: 'SALT cap of $10,000 total for lines 5a+5b+5c',
  },
  {
    id: 'real_estate_tax',
    label: 'Real Estate Taxes',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_A,
    form: 'Schedule A',
    line: 'Line 5b',
    lineDescription: 'State and local real estate taxes',
    txfCode: 'N523',
    description: 'Property taxes on primary residence',
    notes: 'Subject to $10,000 SALT cap',
    requiresDoc: 'Property tax statements',
  },
  {
    id: 'personal_property_tax',
    label: 'Personal Property Taxes',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_A,
    form: 'Schedule A',
    line: 'Line 5c',
    lineDescription: 'State and local personal property taxes',
    txfCode: 'N526',
    description: 'Vehicle registration (value-based portion), etc.',
    notes: 'Subject to $10,000 SALT cap',
  },
  {
    id: 'mortgage_interest',
    label: 'Home Mortgage Interest',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_A,
    form: 'Schedule A',
    line: 'Line 8a',
    lineDescription: 'Home mortgage interest and points reported on Form 1098',
    txfCode: 'N503',
    description: 'Mortgage interest on primary/second home',
    requiresDoc: 'Form 1098 from mortgage lender',
    notes: 'Principal portion is NOT deductible - split transactions accordingly',
  },
  {
    id: 'mortgage_points',
    label: 'Mortgage Points Paid',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_A,
    form: 'Schedule A',
    line: 'Line 8c',
    lineDescription: 'Points not reported on Form 1098',
    txfCode: 'N506',
    description: 'Points paid on home purchase/refinance',
    notes: 'Refinance points typically amortized over loan term',
  },
  {
    id: 'charitable_cash',
    label: 'Charitable Contributions - Cash',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_A,
    form: 'Schedule A',
    line: 'Line 11',
    lineDescription: 'Gifts by cash or check',
    txfCode: 'N483',
    description: 'Cash/check donations to qualified 501(c)(3) orgs',
    notes: 'Donations over $250 require written acknowledgment from charity',
    requiresDoc: 'Receipts from charity (required for any donation $250+)',
  },
  {
    id: 'charitable_noncash',
    label: 'Charitable Contributions - Non-Cash',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_A,
    form: 'Schedule A',
    line: 'Line 12',
    lineDescription: 'Other than by cash or check',
    txfCode: 'N484',
    description: 'Donated goods (clothes, furniture, etc.)',
    notes: 'Donations over $500 require Form 8283',
    requiresDoc: 'Receipts and fair market value documentation',
  },
  {
    id: 'charitable_mileage',
    label: 'Charitable Mileage',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_A,
    form: 'Schedule A',
    line: 'Line 11',
    lineDescription: 'Gifts by cash or check (mileage)',
    txfCode: 'N485',
    description: 'Miles driven for charitable purposes',
    notes: 'IRS rate: 14 cents/mile (verify current year rate)',
  },
  {
    id: 'casualty_theft_loss',
    label: 'Casualty & Theft Losses',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_A,
    form: 'Schedule A',
    line: 'Line 15',
    lineDescription: 'Casualty and theft losses',
    txfCode: 'N527',
    description: 'Losses from federally declared disasters',
    notes: 'Only federally declared disaster losses currently deductible',
  },

  // ===========================================================================
  // SCHEDULE C - BUSINESS EXPENSES (Self-Employed)
  // ===========================================================================
  {
    id: 'sch_c_advertising',
    label: 'Schedule C - Advertising',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 8',
    lineDescription: 'Advertising',
    txfCode: 'N304',
    description: 'Business marketing, ads, website costs',
  },
  {
    id: 'sch_c_car_truck',
    label: 'Schedule C - Car & Truck Expenses',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 9',
    lineDescription: 'Car and truck expenses',
    txfCode: 'N305',
    description: 'Business vehicle expenses (mileage OR actual)',
    notes: 'Choose standard mileage OR actual expenses method',
  },
  {
    id: 'sch_c_commissions',
    label: 'Schedule C - Commissions & Fees',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 10',
    lineDescription: 'Commissions and fees',
    txfCode: 'N306',
    description: 'Commissions paid to non-employees',
  },
  {
    id: 'sch_c_contract_labor',
    label: 'Schedule C - Contract Labor',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 11',
    lineDescription: 'Contract labor',
    txfCode: 'N492',
    description: 'Payments to independent contractors',
    notes: 'Issue 1099-NEC for contractors paid $600+',
  },
  {
    id: 'sch_c_depreciation',
    label: 'Schedule C - Depreciation',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 13',
    lineDescription: 'Depreciation and section 179 expense',
    txfCode: 'N307',
    description: 'Depreciation on business assets',
    notes: 'Requires Form 4562',
  },
  {
    id: 'sch_c_insurance',
    label: 'Schedule C - Insurance (not health)',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 15',
    lineDescription: 'Insurance (other than health)',
    txfCode: 'N308',
    description: 'Business insurance (liability, property)',
  },
  {
    id: 'sch_c_mortgage_interest',
    label: 'Schedule C - Mortgage Interest (Business)',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 16a',
    lineDescription: 'Interest - Mortgage (paid to banks, etc.)',
    txfCode: 'N309',
    description: 'Mortgage interest on business property',
  },
  {
    id: 'sch_c_other_interest',
    label: 'Schedule C - Other Interest',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 16b',
    lineDescription: 'Interest - Other',
    txfCode: 'N310',
    description: 'Business credit card interest, loan interest',
  },
  {
    id: 'sch_c_legal_professional',
    label: 'Schedule C - Legal & Professional Services',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 17',
    lineDescription: 'Legal and professional services',
    txfCode: 'N311',
    description: 'Accountant, lawyer, consultant fees',
  },
  {
    id: 'sch_c_office',
    label: 'Schedule C - Office Expense',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 18',
    lineDescription: 'Office expense',
    txfCode: 'N312',
    description: 'Office supplies, postage, small equipment',
  },
  {
    id: 'sch_c_rent_equipment',
    label: 'Schedule C - Rent (Equipment)',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 20a',
    lineDescription: 'Rent on vehicles, machinery, equipment',
    txfCode: 'N314',
    description: 'Equipment rental costs',
  },
  {
    id: 'sch_c_rent_property',
    label: 'Schedule C - Rent (Property)',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 20b',
    lineDescription: 'Rent on other business property',
    txfCode: 'N315',
    description: 'Office/business space rent',
  },
  {
    id: 'sch_c_repairs',
    label: 'Schedule C - Repairs & Maintenance',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 21',
    lineDescription: 'Repairs and maintenance',
    txfCode: 'N316',
    description: 'Business equipment/property repairs',
  },
  {
    id: 'sch_c_supplies',
    label: 'Schedule C - Supplies',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 22',
    lineDescription: 'Supplies',
    txfCode: 'N317',
    description: 'Business supplies (non-office)',
  },
  {
    id: 'sch_c_taxes_licenses',
    label: 'Schedule C - Taxes & Licenses',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 23',
    lineDescription: 'Taxes and licenses',
    txfCode: 'N318',
    description: 'Business licenses, registrations, payroll taxes',
  },
  {
    id: 'sch_c_travel',
    label: 'Schedule C - Travel',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 24a',
    lineDescription: 'Travel',
    txfCode: 'N319',
    description: 'Business travel (transportation, lodging)',
    notes: 'Does NOT include meals - use separate category',
  },
  {
    id: 'sch_c_meals',
    label: 'Schedule C - Meals (50% deductible)',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 24b',
    lineDescription: 'Deductible meals',
    txfCode: 'N320',
    description: 'Business meals (enter full amount, 50% auto-applied)',
    notes: 'Only 50% deductible - set deductible_percentage to 50',
    defaultDeductiblePct: 50,
  },
  {
    id: 'sch_c_utilities',
    label: 'Schedule C - Utilities',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 25',
    lineDescription: 'Utilities',
    txfCode: 'N322',
    description: 'Business utilities (not home office)',
  },
  {
    id: 'sch_c_wages',
    label: 'Schedule C - Wages',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 26',
    lineDescription: 'Wages (less employment credits)',
    txfCode: 'N323',
    description: 'W-2 wages paid to employees',
  },
  {
    id: 'sch_c_other',
    label: 'Schedule C - Other Expenses',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 27a',
    lineDescription: 'Other expenses',
    txfCode: 'N324',
    description: 'Business expenses not fitting other categories',
  },
  {
    id: 'sch_c_home_office',
    label: 'Schedule C - Home Office',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_C,
    form: 'Schedule C',
    line: 'Line 30',
    lineDescription: 'Expenses for business use of your home',
    txfCode: 'N491',
    description: 'Home office deduction',
    notes: 'Requires Form 8829 or simplified method ($5/sq ft up to 300 sq ft)',
  },

  // ===========================================================================
  // SCHEDULE E - RENTAL EXPENSES
  // ===========================================================================
  {
    id: 'sch_e_advertising',
    label: 'Schedule E - Advertising',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 5',
    lineDescription: 'Advertising',
    txfCode: 'N439',
    description: 'Rental property listing/advertising',
  },
  {
    id: 'sch_e_auto_travel',
    label: 'Schedule E - Auto & Travel',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 6',
    lineDescription: 'Auto and travel',
    txfCode: 'N440',
    description: 'Travel to/from rental property',
  },
  {
    id: 'sch_e_cleaning',
    label: 'Schedule E - Cleaning & Maintenance',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 7',
    lineDescription: 'Cleaning and maintenance',
    txfCode: 'N441',
    description: 'Regular cleaning, landscaping, maintenance',
  },
  {
    id: 'sch_e_commissions',
    label: 'Schedule E - Commissions',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 8',
    lineDescription: 'Commissions',
    txfCode: 'N442',
    description: 'Leasing commissions paid',
  },
  {
    id: 'sch_e_insurance',
    label: 'Schedule E - Insurance',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 9',
    lineDescription: 'Insurance',
    txfCode: 'N443',
    description: 'Landlord insurance',
  },
  {
    id: 'sch_e_legal',
    label: 'Schedule E - Legal & Professional',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 10',
    lineDescription: 'Legal and other professional fees',
    txfCode: 'N444',
    description: 'Attorney/CPA fees for rental',
  },
  {
    id: 'sch_e_management',
    label: 'Schedule E - Management Fees',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 11',
    lineDescription: 'Management fees',
    txfCode: 'N445',
    description: 'Property management company fees',
  },
  {
    id: 'sch_e_mortgage_interest',
    label: 'Schedule E - Mortgage Interest',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 12',
    lineDescription: 'Mortgage interest paid to banks, etc.',
    txfCode: 'N446',
    description: 'Mortgage interest on rental property',
    notes: 'Principal is NOT deductible - split transactions',
  },
  {
    id: 'sch_e_other_interest',
    label: 'Schedule E - Other Interest',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 13',
    lineDescription: 'Other interest',
    txfCode: 'N447',
    description: 'Other rental-related interest',
  },
  {
    id: 'sch_e_repairs',
    label: 'Schedule E - Repairs',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 14',
    lineDescription: 'Repairs',
    txfCode: 'N448',
    description: 'Rental property repairs (not improvements)',
    notes: 'Improvements must be capitalized and depreciated',
  },
  {
    id: 'sch_e_supplies',
    label: 'Schedule E - Supplies',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 15',
    lineDescription: 'Supplies',
    txfCode: 'N449',
    description: 'Supplies for rental property',
  },
  {
    id: 'sch_e_taxes',
    label: 'Schedule E - Taxes',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 16',
    lineDescription: 'Taxes',
    txfCode: 'N450',
    description: 'Property taxes on rental',
  },
  {
    id: 'sch_e_utilities',
    label: 'Schedule E - Utilities',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 17',
    lineDescription: 'Utilities',
    txfCode: 'N451',
    description: 'Utilities paid by landlord',
  },
  {
    id: 'sch_e_depreciation',
    label: 'Schedule E - Depreciation',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 18',
    lineDescription: 'Depreciation expense or depletion',
    txfCode: 'N452',
    description: 'Depreciation on rental property',
    notes: 'Requires Form 4562',
  },
  {
    id: 'sch_e_other',
    label: 'Schedule E - Other Expenses',
    type: TAX_TYPES.DEDUCTION,
    schedule: TAX_SCHEDULES.SCHEDULE_E,
    form: 'Schedule E',
    line: 'Line 19',
    lineDescription: 'Other',
    txfCode: 'N453',
    description: 'Other rental expenses',
  },

  // ===========================================================================
  // SCHEDULE 1 - ADJUSTMENTS TO INCOME (Above-the-line deductions)
  // ===========================================================================
  {
    id: 'hsa_contribution',
    label: 'HSA Contributions',
    type: TAX_TYPES.ADJUSTMENT,
    schedule: TAX_SCHEDULES.SCHEDULE_1,
    form: 'Schedule 1',
    line: 'Line 13',
    lineDescription: 'Health savings account deduction',
    txfCode: 'N608',
    description: 'HSA contributions (after-tax)',
    requiresDoc: 'Form 8889',
    notes: 'Do NOT include employer contributions or pre-tax payroll deductions',
  },
  {
    id: 'self_employment_tax_deduction',
    label: 'Self-Employment Tax Deduction',
    type: TAX_TYPES.ADJUSTMENT,
    schedule: TAX_SCHEDULES.SCHEDULE_1,
    form: 'Schedule 1',
    line: 'Line 15',
    lineDescription: 'Deductible part of self-employment tax',
    txfCode: 'N283',
    description: 'Half of self-employment tax',
    notes: 'Calculated automatically from Schedule SE',
  },
  {
    id: 'sep_simple_pension',
    label: 'SEP, SIMPLE, and Qualified Plans',
    type: TAX_TYPES.ADJUSTMENT,
    schedule: TAX_SCHEDULES.SCHEDULE_1,
    form: 'Schedule 1',
    line: 'Line 16',
    lineDescription: 'Self-employed SEP, SIMPLE, and qualified plans',
    txfCode: 'N284',
    description: 'Self-employed retirement plan contributions',
  },
  {
    id: 'se_health_insurance',
    label: 'Self-Employed Health Insurance',
    type: TAX_TYPES.ADJUSTMENT,
    schedule: TAX_SCHEDULES.SCHEDULE_1,
    form: 'Schedule 1',
    line: 'Line 17',
    lineDescription: 'Self-employed health insurance deduction',
    txfCode: 'N602',
    description: 'Health insurance premiums for self-employed',
    notes: 'Limited to self-employment income',
  },
  {
    id: 'traditional_ira',
    label: 'Traditional IRA Contribution',
    type: TAX_TYPES.ADJUSTMENT,
    schedule: TAX_SCHEDULES.SCHEDULE_1,
    form: 'Schedule 1',
    line: 'Line 20',
    lineDescription: 'IRA deduction',
    txfCode: 'N002',
    description: 'Traditional IRA contributions',
    notes: 'Subject to income limits and contribution caps',
  },
  {
    id: 'student_loan_interest',
    label: 'Student Loan Interest',
    type: TAX_TYPES.ADJUSTMENT,
    schedule: TAX_SCHEDULES.SCHEDULE_1,
    form: 'Schedule 1',
    line: 'Line 21',
    lineDescription: 'Student loan interest deduction',
    txfCode: 'N612',
    description: 'Interest paid on qualified student loans',
    requiresDoc: 'Form 1098-E',
    notes: 'Maximum $2,500 deduction, subject to income limits',
  },
  {
    id: 'educator_expenses',
    label: 'Educator Expenses',
    type: TAX_TYPES.ADJUSTMENT,
    schedule: TAX_SCHEDULES.SCHEDULE_1,
    form: 'Schedule 1',
    line: 'Line 11',
    lineDescription: 'Educator expenses',
    txfCode: 'N609',
    description: 'K-12 teacher classroom expenses (up to $300)',
    notes: 'Limit: $300 per eligible educator',
  },

  // ===========================================================================
  // CREDITS (tracked but entered on credit forms)
  // ===========================================================================
  {
    id: 'tuition_payments',
    label: '1098-T Tuition Payments',
    type: TAX_TYPES.CREDIT,
    schedule: TAX_SCHEDULES.SCHEDULE_3,
    form: 'Form 8863',
    line: 'Multiple',
    lineDescription: 'Tuition payments for education credits',
    txfCode: 'N611',
    description: 'Qualified tuition (American Opportunity/Lifetime Learning)',
    requiresDoc: 'Form 1098-T',
  },
  {
    id: 'child_care_expenses',
    label: 'Child & Dependent Care',
    type: TAX_TYPES.CREDIT,
    schedule: TAX_SCHEDULES.SCHEDULE_3,
    form: 'Form 2441',
    line: 'Multiple',
    lineDescription: 'Child and dependent care expenses',
    txfCode: 'N401',
    description: 'Daycare, after-school care (for credit)',
    requiresDoc: 'Provider name, address, and Tax ID',
  },

  // ===========================================================================
  // PAYMENTS
  // ===========================================================================
  {
    id: 'estimated_tax_federal',
    label: 'Federal Estimated Tax Payment',
    type: TAX_TYPES.PAYMENT,
    schedule: TAX_SCHEDULES.FORM_1040,
    form: 'Form 1040',
    line: 'Line 26',
    lineDescription: '2024 estimated tax payments',
    txfCode: 'N521',
    description: 'Quarterly estimated tax payments (Form 1040-ES)',
  },
  {
    id: 'estimated_tax_state',
    label: 'State Estimated Tax Payment',
    type: TAX_TYPES.PAYMENT,
    schedule: TAX_SCHEDULES.SCHEDULE_A,
    form: 'Schedule A',
    line: 'Line 5a',
    lineDescription: 'State estimated tax payments (also a SALT deduction)',
    txfCode: 'N522',
    description: 'Quarterly state estimated tax payments',
    notes: 'Deductible as SALT (subject to $10,000 cap)',
  },

  // ===========================================================================
  // PERSONAL (Non-Deductible) - used to mark obviously non-tax transactions
  // ===========================================================================
  {
    id: 'personal_nondeductible',
    label: 'Personal - Not Tax Relevant',
    type: TAX_TYPES.PERSONAL,
    schedule: TAX_SCHEDULES.PERSONAL,
    form: 'N/A',
    line: 'N/A',
    lineDescription: 'Not applicable',
    txfCode: null,
    description: 'Personal expenses with no tax impact',
  },
];

// -----------------------------------------------------------------------------
// LOOKUP HELPERS
// -----------------------------------------------------------------------------

/**
 * Get a tax category by its id.
 */
export function getTaxCategoryById(id) {
  return TAX_CATEGORIES.find(c => c.id === id) || null;
}

/**
 * Get all categories for a given schedule.
 */
export function getCategoriesBySchedule(schedule) {
  return TAX_CATEGORIES.filter(c => c.schedule === schedule);
}

/**
 * Get all categories of a given type.
 */
export function getCategoriesByType(type) {
  return TAX_CATEGORIES.filter(c => c.type === type);
}

/**
 * Get all unique schedules in use.
 */
export function getAllSchedules() {
  return [...new Set(TAX_CATEGORIES.map(c => c.schedule))];
}

/**
 * Build a grouped structure for dropdowns (group by schedule).
 */
export function getCategoriesGrouped() {
  const groups = {};
  TAX_CATEGORIES.forEach(c => {
    if (!groups[c.schedule]) groups[c.schedule] = [];
    groups[c.schedule].push(c);
  });
  return groups;
}
